### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by feishuai93** [cypw/DPNs#5]
hi, when i run score.py, there is a such mistake:
Traceback (most recent call last):
  File "D:/PycharmProjects/DPNs-master/score.py", line 110, in <module>
    speed = score(metrics=metrics, **vars(args))
  File "D:/PycharmProjects/DPNs-master/score.py", line 42, in score
    inter_method=2  # bicubic   
  File "D:\Python35\lib\site-packages\mxnet\io.py", line 725, in creator
    ctypes.byref(iter_handle)))
OSError: exception: access violation reading 0x0000000000000090
can you help me ,thanks a lot.

**Comment by ufwtsmqy** [comment]
我也遇到这个问题，请问您解决这个问题了吗
